# Generated by Django 2.0.5 on 2018-06-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='gender',
        ),
    ]
